config/routes.rb
Rails.application.routes.draw do
  # customer側ルーティング
   devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    root 'homes#top'
    get 'about' => 'homes#about'
   end

  namespace :customers do
   resources :items, only: [:show]
   resources :genres, only: [:show]
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'orders/complete' => 'orders#complete'
   post 'orders/comfirm' => 'orders#comfirm'
   resources :orders, only: [:new, :create, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
   devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'orders#index'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  
  
  # 退会
    def active_for_authentication?
      super && (self.is_deleted == false)
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
 
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @search = Customer.ransack(params[:q])
    @customers = @search.result.page(params[:page]).per(10)
    
  end 
  
  def show
    @customer = Customer.find(params[:id])
  end 
  
  def edit
    @customer = Customer.find(params[:id])
  end 
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
      flash[:notice_update] = "会員情報を更新しました！"
    else
      edit_admins_customer_path(@customer)
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
		@order = Order.ransack(params[:q])
    @orders = @order.result.page(params[:page]).per(10)
  end

  def show

    @order = Order.find(params[:id])
		@order_details = @order.order_details
		@customer = @order.customer
  end

	def update
		@order = Order.find(params[:id])
		@order_details = @order.order_details
    @order.update(order_params)
		if @order.order_status == "入金確認"
			 @order_details.update_all(making_status: "製作待ち")
		end
		redirect_to admins_order_path(@order)
	end

  private
	def order_params
		params.require(:order).permit(:payment_method, :order_status)
	end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
  before_action :authenticate_customer!

    # 配送先一覧/配送先登録画面
    def index
        @address = Address.new
        @addresses = current_customer.addresses
    end
    # 配送先登録ボタン
    def create
        @address = Address.new(address_params)
        @address.customer_id = current_customer.id
        @address.save
        if @address.update(address_params)
            redirect_to customers_addresses_path
            flash[:address] = "登録しました。"
        else
            render customers_addresses_path
        end
    end
    # 配送先編集ボタン
    def edit
        @address = Address.find(params[:id])
    end
    # 配送先編集保存ボタン
    def update
        address = Address.find(params[:id])
        address.update(address_params)
        redirect_to customers_addresses_path
        flash[:address] = "編集しました。"
    end

    # 配送先を削除する
    def destroy
        address = Address.find(params[:id])
        address.destroy
        redirect_to customers_addresses_path
        flash[:address] = "削除しました。"
    end





    private
    def address_params
        params.require(:address).permit(:customer_id, :name, :postal_code, :address)
    end




end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :authenticate_customer!
    # カート商品一覧を表示
    def index
        @cart_items = current_customer.cart_items
        @total_price = @cart_items.sum{|cart_item|cart_item.item.price_without_tax * cart_item.amount * 1.1}
        # sumメソッド：合計金額を出す
        # 1行目の@cart_itemsにsumメソッドを用いて{}の||ブロック変数にcart_itemを代入している。(each do || end の文章と同じイメージ)
        # cart_item.item.price_without_tax：アソシエーションしているのでドットでつなげる。
        # 『このcart_itemのitemのprice_without_tax』 → 『このカート商品の商品（単体）の税抜き価格』
        # cart_item.quantity：『このカート商品の個数』
    end
    # カート商品を追加する
    def create
        # @cart_item = current_customer.cart_items.build(item_id: params[:item_id])
        @cart_item = CartItem.new(cart_item_params)
        @cart_item.customer_id = current_customer.id
        @cart_item.item_id = params[:item_id]
        # byebug

        if @cart_item.save
           flash[:notice] = "#{@cart_item.item.name}をカートに追加しました。"
           redirect_to customers_cart_items_path
        else
            flash[:alert] = "個数を選択してください"
            render "customers/items/show"
        end
    end

    # 削除や個数を変更した際、カート商品を再計算する
    def update
        @cart_item = CartItem.find(params[:id])
        #@cart.units += cart_params[:units].to_i
        @cart_item.update(cart_item_params)
        redirect_to customers_cart_items_path
    end

    # カート商品を一つのみ削除
    def destroy
        @cart_item = CartItem.find(params[:id])
        @cart_item.destroy
        flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
        redirect_to customers_cart_items_path
    end

    # カート商品を空ににする
    def destroy_all
        @cart_item = current_customer.cart_items
        @cart_item.destroy_all
        flash[:alert] = "カートの商品を全て削除しました"
        redirect_to customers_cart_items_path
    end

    private

      def cart_item_params
        params.require(:cart_item).permit(:amount, :item_id, :customer_id)
      end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!

    # マイページへのアクション
    def show
        @customer = current_customer
    end
    # 登録情報編集へのアクション
    def edit
        @customer = current_customer
    end
    # 登録情報の編集を保存するアクション
    def update
        @customer = current_customer
        if @customer.update(customer_params)
        else
            render 'edit'
        end
    end
    # 登録情報編集画面から退会ページを表示するアクション
    def unsubscribe
    end
    # 退会アクション
    def withdraw
        @customer = current_customer
        
        # is_customer_statusカラムにフラグを立てる(default→false(有効状態)をtrue(無効状態)にする）
        @customer.update(is_deleted: true)
        # ログアウトさせる
        reset_session

        flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
        redirect_to root_path
    end

    private
        def customer_params
            params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
        end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def top
  @genres = Genre.all
  @items = Item.all
  end
  def about
  end 
  
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  
def index
  @genres = Genre.all
  @item = Item.ransack(params[:q])
  @items = @item.result.page(params[:page]).per(8)
  @items_all = Item.all
end

 
def show
  @item = Item.find(params[:id])
  @cart_item = CartItem.new
  @genres = Genre.all
end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
	before_action :authenticate_customer!
	#注文情報入力画面
	def new
	    @customer = current_customer
	    @order = Order.new
	end
	#注文情報確認画面
	def comfirm
	  	customer = current_customer
	  	# @order = Order.new
	  	@cart_items = customer.cart_items
	  	session[:order] = Order.new
		# 送料
		session[:order][:shopping_cost] = 800
		# 小計（商品合計）
		total = @cart_items.sum{|cart_item|cart_item.item.price_without_tax * cart_item.amount * 1.1 }.floor
		# 請求額
		session[:order][:total_payment] = total + session[:order][:shopping_cost]
		session[:order][:order_status] = 0
		session[:order][:customer_id] = customer.id
		# ラジオボタンで選択された支払方法のenum番号を渡してい
		session[:order][:payment_method] = params[:order][:payment_method]

		# ご自身の住所が選択された時
		if params[:order][:a_method] == "0"

			session[:order][:postal_code] = customer.postal_code
			session[:order][:address] = customer.address
			session[:order][:name] = customer.last_name + " " + customer.first_name

		# 登録済住所が選択された時
		elsif params[:order][:a_method] == "1"

			address = Address.find(params[:order][:dear_address])
			session[:order][:postal_code] = address.postal_code
			session[:order][:address] = address.address
			session[:order][:name] = address.name

		# 新しいお届け先が選択された時
		elsif params[:order][:a_method] == "2"

			session[:order][:postal_code] = params[:order][:postal_code]
			session[:order][:address] = params[:order][:address]
			session[:order][:name] = params[:order][:name]

		end

	end

	#注文完了画面の前の処理
	def create
		order = Order.new(session[:order])
		order.save
		# 以下、order_detail作成
		cart_items = current_customer.cart_items

		cart_items.each do |cart_item|
			order_detail = OrderDetail.new
			order_detail.order_id = order.id
			order_detail.item_id = cart_item.item.id
			order_detail.amount = cart_item.amount
			order_detail.making_status = 0
			order_detail.price = (cart_item.item.price_without_tax * 1.1).floor
			order_detail.save
		end
		# 購入後はカート内商品削除
		cart_items.destroy_all
		redirect_to customers_orders_complete_path
	end

	def complete
	end

	def index
		@orders = current_customer.orders
		# @order_details = @order.page(params[:page]).per(10)
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end


	private
	    def order_params
	        params.require(:order).permit(:customer_id, :shopping_cost, :total_payment, :payment_method, :order_status, :postal_code, :address, :name)
	    end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/customers/orders/comfirm.html.erb
<div class =" container">
  <div class="row">
    <h3><strong>注文情報確認</strong></h3>

    <div class="col-xs-9">
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag( cart_item.item, :image, size: "60x50", fallback: "no_image.jpg") %>
                <%= cart_item.item.name %>
              </td>
              <td class="text-right">
                ¥<%= cart_item.item.with_tax_price %>
              </td>
              <td class="text-right">
                  <%= cart_item.amount %>
              </td>
              <td class="text-right">
                ¥<%= cart_item.subtotal %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-9">
      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-left">¥<%= session[:order]["shopping_cost"] %></td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-left">¥<%=session[:order]["total_payment"] - session[:order]["shopping_cost"] %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-left">¥<%= session[:order]["total_payment"] %></td>
          </tr>
      </table>
    </div>
    <div class="col-xs-9">
      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= session[:order]["payment_method"] %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= session[:order]["postal_code"] %><br>
            <%= session[:order]["address"] %><br>
            <%= session[:order]["name"] %><br>
          </td>
        </tr>
      </table>
      <%= link_to "注文を確定する", customers_orders_path, method: :post, class: 'btn btn-primary col-xs-12'%>
      <%#= form_with model: @order, url: customers_orders_path, method: :post, local: true do |f| %>
      <%#= f.hidden_field :customer_id, value: current_customer.id %>
      <%#= f.hidden_field :postal_code, value: @order.postal_code %>
      <%#= f.hidden_field :address, value: @order.address %>
      <%#= f.hidden_field :name, value: @order.name %>
      <%#= f.hidden_field :shopping_cost, value: 800 %>
      <%#= f.hidden_field :payment_method, value: @order.payment_method %>
      <%#= f.hidden_field :order_status, value: "入金待ち" %>
      <%#= f.hidden_field :total_payment, value: session[:order][:total_payment] %>
      <%#= f.submit "注文を確定する", class: 'btn btn-primary col-xs-12' %>
      <%# end %>
    </div>
  </div>
</div>

app/views/customers/orders/compleate.html.erb
<body>
	<div class="thankspage">
		<h1 class="message">ご注文ありがとうございました！</h1>
	</div>
</body>

app/views/customers/orders/complete.html.erb
<body>
	<div class="thankspage">
		<h1 class="message">ご注文ありがとうございました！</h1>
	</div>
</body>

app/views/customers/orders/index.html.erb
<div class="row">
	<div class="col-xs-12">
		<h3><strong>注文履歴一覧</strong></h3>
		<table class="table table-bordered table-condensed">
			<tr>
				<th class="col-xs-1">注文日</th>
				<th class="col-xs-4">配送先</th>
				<th class="col-xs-2">注文商品</th>
				<th class="col-xs-1">支払金額</th>
				<th class="col-xs-1">ステータス</th>
				<th class="col-xs-2">注文詳細</th>
			</tr>
		<% @orders.each do |order|%>
			<tr>
				<td class="col-xs-1"><%= l order.created_at %></td>
				<td class="col-xs-4"><%= order.postal_code %><br>
					<%= order.address %><br>
					<%= order.name %>
				</td>
				<td class="col-xs-2">
					<% order.order_details.each do |order_detail| %>
					<%= order_detail.item.name %><br>
				<% end %>
				</td>
				<td class="col-xs-1"><%= order.total_payment.to_s(:delimited, delimiter: ',') %></td>
				<td class="col-xs-1"><%= order.order_status %></td>
				<td><%= link_to "表示する", customers_order_path(order), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
		</table>
	</div>
</div>

app/views/customers/orders/new.html.erb
<body>
	<div class="panel panel-warning">
		<div class="panel-heading">
	<h2><span class="label label-default">注文情報入力</span></h2>
	</div>
	<div class="panel-body">

		<%= form_with model: @order, url: customers_orders_comfirm_path, method: :post, local: true do |f| %>
		<h3>支払方法</h3>
			<!-- form.radio_button :カラム名, :保存される値(enumの番号) -->
			<span>　　　</span><%= f.radio_button :payment_method, "クレジットカード", checked: "checked" %>
  		<%= f.label :クレジットカード %><br>
  		<span>　　　</span><%= f.radio_button :payment_method, "銀行振込" %>
  		<%= f.label :銀行振込 %>

		<h3>お届け先</h3>
			<span>　　　</span>
			<%= f.radio_button :a_method, 0, checked: "checked" %>
				<%= f.label :ご自身の住所 %><br>
				<span>　　　　　</span>
				<%= @customer.postal_code %>&emsp;<%= @customer.address %><br>
				<span>　　　　　</span>
				<%= @customer.last_name %>&emsp;<%= @customer.first_name %><br>
			<br>
			<span>　　　</span>
			<%= f.radio_button :a_method, 1 %>
				<%= f.label :登録済住所から選択 %><br>
				<!-- collection_select(プロパティ名, オブジェクトの配列, value属性の項目, テキストの項目 [, オプション])-->
				<span>　　　　　</span><%= f.collection_select :dear_address, current_customer.addresses, :id, :address_for_view %><br>
				<br>
			<span>　　　</span>
			<%= f.radio_button :a_method, 2 %>
				<%= f.label :新しいお届け先 %><br>
				<div class="form-group col-xs-12">
				<span>　　</span>
				<%= f.label :"　　　郵便番号(ハイフンなし)", class: "col-xs-3 control-label"  %>
				<%= f.text_field :postal_code, class: "col-xs-4 form-control-static postal_code" %>
				</div>
				<div class="form-group col-xs-12">
				<span>　　</span>
				<%= f.label :"　　　住所", class: "col-xs-3 control-label" %>
				<%= f.text_field :address, class: "col-xs-7 form-control-static address" %>
				</div>
				<div class="form-group col-xs-12">
				<span>　　</span>
				<%= f.label :"　　　宛名", class: "col-xs-3 control-label" %>
				<%= f.text_field :name, class: "col-xs-4 form-control-static name"%>
				</div>
	  <%= f.submit "確認画面へ進む", class: 'btn btn-warning col-xs-6 col-xs-offset-1'%>
		<% end %>
	</div>
</body>

app/views/customers/orders/show.html.erb
<h3><strong>注文履歴詳細</strong></h3>

<div calss="row">
    <div class="col-xs-8">
    	<strong>注文情報</strong>
  	    <table class="table table-bordered table-condensed">
          <tbody>
              <tr>
                <th class="info", bgcolor="#d7cebb">注文日</th>
          	    <td class="text-left">

                  <%= l @order.created_at %>
                </td>
              </tr>
              <tr>
                <th class="info", bgcolor="#d7cebb">配送先</th>
                <td class="text-left">
                  <%= @order.postal_code %><br>
                  <%= @order.address %><br>
                  <%= @order.name %>
                </td>
              </tr>
              <tr>
                <th class="info", bgcolor="#d7cebb">支払方法</th>
                <td class="text-left">
                  <%= @order.payment_method %>
                </td>
              </tr>
              <tr>
                <th class="info", bgcolor="#d7cebb">ステータス</th>
                <td class="text-left">
                  <%= @order.order_status %>
                </td>
              </tr>
          </tbody>
        </table>
    </div>

    <div class="col-xs-3 billing">
      <strong>請求情報</strong>
        <table class="table  table-bordered table-condensed">
            <tr>
              <th class="info", bgcolor="#d7cebb">商品合計</th>
              <td class="col-xs-5">
                ¥<%= (@order.total_payment - @order.shopping_cost ).to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
            <tr>
              <th class="info", bgcolor="#d7cebb">配送料</th>
              <td class="col-xs-5">
                ¥<%= @order.shopping_cost.to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
            <tr>
              <th class="info", bgcolor="#d7cebb">ご請求金額</th>
              <td class="col-xs-5">
                ¥<%= @order.total_payment.to_s(:delimited, delimiter: ',') %>
              </td>
            </tr>
        </table>
    </div>
    <div class="col-xs-7 order-details">
    	<strong>注文内容</strong>
        <table class="table table-striped table-bordered table-condensed">
          <thead>
            <tr class="info">
                <th bgcolor="#d7cebb">商品</th>
                <th bgcolor="#d7cebb">単価(税込)</th>
                <th bgcolor="#d7cebb">個数</th>
                <th bgcolor="#d7cebb">小計</th>
            </tr>
          </thead>
          <tbody>
        	<% @order_details.each do |order_detail| %>
            <tr>
                <td><%= order_detail.item.name %></td>
                <td>¥<%= ((order_detail.item.price_without_tax * 1.1).floor).to_s(:delimited, delimiter: ',') %></td>
                <td><%= order_detail.amount %></td>
                <td>¥<%= ((order_detail.item.price_without_tax * 1.1).floor * (order_detail.amount)).to_s(:delimited, delimiter: ',') %></td>
            </tr>
          <% end %>
          </tbody>
         
        </table>
    </div>
</div>