config/routes.rb
Rails.application.routes.draw do
  # customer側ルーティング
   devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    root 'homes#top'
    get 'about' => 'homes#about'
   end

  namespace :customers do
   resources :items, only: [:show]
   resources :genres, only: [:show]
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'orders/complete' => 'orders#complete'
   post 'orders/comfirm' => 'orders#comfirm'
   resources :orders, only: [:new, :create, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
   devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'orders#index'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  
  
  # 退会
    def active_for_authentication?
      super && (self.is_deleted == false)
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  attachment :image
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price_without_tax, presence: true

  ## 消費税を求めるメソッド
  def with_tax_price
      (price_without_tax * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/models/project.rb
class Project < ApplicationRecord
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]


  def index
    @item = Item.ransack(params[:q])
    @items = @item.result.page(params[:page]).per(10)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_items_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を選択してください"
      redirect_to new_admins_item_path
      # render 'index'
    end
  end
  
  
  def new
    @items = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admins_item_path(@item)
      # render 'edit'
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price_without_tax, :image, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin then
        admins_root_path
      when Customer then
        root_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  
def index
  @genres = Genre.all
  @item = Item.ransack(params[:q])
  @items = @item.result.page(params[:page]).per(8)
  @items_all = Item.all
end

 
def show
  @item = Item.find(params[:id])
  @cart_item = CartItem.new
  @genres = Genre.all
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    #ViewのFormで取得したパラメータをモデルに渡す
    @projects = Project.search(params[:search])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admins/items/edit.html.erb
<h2>商品編集</h2>
<br>
<%= form_with model: @item, url: admins_item_path, local: true do |f| %>
  <table class="new-form-table">
    <div class="col-xs-8">
    <tbody>
      <tr>
        <th>商品画像</th>
        <td>
          <div class="item-new-form">
            <%= f.attachment_field :image %>
          </div>
        </td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name, class: "form-control" %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :introduction, class: "form-control" %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :price_without_tax, class: "form-control" %></td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, "販売中"  %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "販売停止中" %>
        </td>
      </tr>
    </tbody>
    </div>
  </table>
  <div class="text-right"><%= f.submit "変更を保存" ,class: "btn btn-success " %></div>
  <% end %>

app/views/admins/items/index.html.erb
<h2>商品一覧</h2>
<div class="text-right">
    <%= link_to "＋" ,new_admins_item_path, class:"btn btn-primary rounded-circle p-2" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name ,admins_item_path(item) %></td>
        <td><%= item.price_without_tax.to_s(:delimited, delimiter: ',') %></td>
        <td><%= item.genre.name %></td>
        <td><% if item.is_active == true %>
              <div class="status_true">販売中</div>
            <% else %>
              <div class="status_false">販売停止中</div>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @items %>

app/views/admins/items/new.html.erb
<%= form_with model: @items, url: admins_items_path, local: true do |f| %>
<h2>商品新規登録</h2>
  <br><br><br>
  <table class="new-form-table">
    <tbody>
      <tr>
        <th>商品画像</th>
        <td>
          <div class="item-new-form">
            <%= f.attachment_field :image %>
          </div>
          <div class="product-img" style="margin-top: 20px;">

          </div>
        </td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name, class: "form-control" %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :introduction, class: "form-control" %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :price_without_tax, class: "form-control" %> <div style ="flex-row">円</div></td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td><%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中"  %></td>
        <td><%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "販売停止中" %></td>
      </tr>
    </tbody>
  </table>
  <%= f.submit "新規登録" ,class: "btn btn-primary" %>
<% end %>

app/views/admins/items/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-4">
      <h2>商品詳細</h2><br>
      <%= attachment_image_tag @item, :image, :fill, 200, 200, fallback: 'no_image.jpg' %>
      <br>
      <div class="col-xs-8">
        <table class="table">
          <tbody>
            <tr>
              <td>商品名</td>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <td>
                税込価格</br>
              （税抜価格）
              </td>
              <td><%= (@item.price_without_tax*1.1).floor.to_s(:delimited, delimiter: ',') %>（<%= (@item.price_without_tax).floor.to_s(:delimited, delimiter: ',') %>）円</td>
            </tr>
            <tr>
              <td>販売ステータス</td>
              <td>
                <div class="item_show_status">
                  <% if @item.is_active == true %>
                    <div class="status_true">販売中</div>
                  <% else %>
                    <div class="status_falese">販売停止中</div>
                  <% end %>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="col-md-offset-1 col-md-2 text-right">
          <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-success" %>
        </div>
      </div>
  </div>
</div>