config/routes.rb
Rails.application.routes.draw do
  # customer側ルーティング
   devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    root 'homes#top'
    get 'about' => 'homes#about'
   end

  namespace :customers do
   resources :items, only: [:show]
   resources :genres, only: [:show]
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'orders/complete' => 'orders#complete'
   post 'orders/comfirm' => 'orders#comfirm'
   resources :orders, only: [:new, :create, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
   devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'orders#index'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
 
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
		@order = Order.ransack(params[:q])
    @orders = @order.result.page(params[:page]).per(10)
  end

  def show

    @order = Order.find(params[:id])
		@order_details = @order.order_details
		@customer = @order.customer
  end

	def update
		@order = Order.find(params[:id])
		@order_details = @order.order_details
    @order.update(order_params)
		if @order.order_status == "入金確認"
			 @order_details.update_all(making_status: "製作待ち")
		end
		redirect_to admins_order_path(@order)
	end

  private
	def order_params
		params.require(:order).permit(:payment_method, :order_status)
	end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
	before_action :authenticate_customer!
	#注文情報入力画面
	def new
	    @customer = current_customer
	    @order = Order.new
	end
	#注文情報確認画面
	def comfirm
	  	customer = current_customer
	  	# @order = Order.new
	  	@cart_items = customer.cart_items
	  	session[:order] = Order.new
		# 送料
		session[:order][:shopping_cost] = 800
		# 小計（商品合計）
		total = @cart_items.sum{|cart_item|cart_item.item.price_without_tax * cart_item.amount * 1.1 }.floor
		# 請求額
		session[:order][:total_payment] = total + session[:order][:shopping_cost]
		session[:order][:order_status] = 0
		session[:order][:customer_id] = customer.id
		# ラジオボタンで選択された支払方法のenum番号を渡してい
		session[:order][:payment_method] = params[:order][:payment_method]

		# ご自身の住所が選択された時
		if params[:order][:a_method] == "0"

			session[:order][:postal_code] = customer.postal_code
			session[:order][:address] = customer.address
			session[:order][:name] = customer.last_name + " " + customer.first_name

		# 登録済住所が選択された時
		elsif params[:order][:a_method] == "1"

			address = Address.find(params[:order][:dear_address])
			session[:order][:postal_code] = address.postal_code
			session[:order][:address] = address.address
			session[:order][:name] = address.name

		# 新しいお届け先が選択された時
		elsif params[:order][:a_method] == "2"

			session[:order][:postal_code] = params[:order][:postal_code]
			session[:order][:address] = params[:order][:address]
			session[:order][:name] = params[:order][:name]

		end

	end

	#注文完了画面の前の処理
	def create
		order = Order.new(session[:order])
		order.save
		# 以下、order_detail作成
		cart_items = current_customer.cart_items

		cart_items.each do |cart_item|
			order_detail = OrderDetail.new
			order_detail.order_id = order.id
			order_detail.item_id = cart_item.item.id
			order_detail.amount = cart_item.amount
			order_detail.making_status = 0
			order_detail.price = (cart_item.item.price_without_tax * 1.1).floor
			order_detail.save
		end
		# 購入後はカート内商品削除
		cart_items.destroy_all
		redirect_to customers_orders_complete_path
	end

	def complete
	end

	def index
		@orders = current_customer.orders
		# @order_details = @order.page(params[:page]).per(10)
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end


	private
	    def order_params
	        params.require(:order).permit(:customer_id, :shopping_cost, :total_payment, :payment_method, :order_status, :postal_code, :address, :name)
	    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/orders/index.html.erb
<h2>注文履歴一覧</h2>
<table class="table">
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to l(order.created_at), admins_order_path(order) %></td>
        <td><%= order.customer.last_name %> <%= order.customer.first_name %></td>
    		<td><%= order.order_details.sum(:amount) %></td>
        <td><%= order.order_status %></td>
    	</tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders %>

app/views/admins/orders/show.html.erb
<h2>注文履歴詳細</h2>
<br><br>
  <table class="table">
      <tbody>
      <tr>
        <th>購入者</th>
        <td><%= link_to @order.customer.last_name+" "+@order.customer.first_name, admins_customer_path(@customer.id) %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%=l( @order.created_at)%></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>〒<%= @order.postal_code %><br>
             <%= @order.address %><br>
             <%= @order.name %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%=form_with model: @order, url: admins_order_path(@order),local: true do |f| %>
          <%= f.select :order_status, Order.order_statuses.keys.to_a %>
          <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <table class="table">
    <thead>
      <tr>
        <th>商品名</th>
        <th>単価（税込）</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @sum = 0 %>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price.floor.to_s(:delimited, delimiter: ',') %></td>
          <td><%= order_detail.amount %></td>
          <td><%= (order_detail.price * order_detail.amount.floor).to_s(:delimited, delimiter: ',') %></td>
          <td>
            <%= form_with model: order_detail, url: admins_order_detail_path(order_detail) do |f|  %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a %>
              <%= f.submit '更新',class:"btn btn-success" %>
            <% end %>
          </td>
        </tr>
      <% @sum += order_detail.price * order_detail.amount %>
      <% end %>
    </tbody>
  </table>
  <table class="table">
    <tbody>
      <tr>
        <th>商品合計</th>
        <td>¥<%= @sum.to_s(:delimited, delimiter: ',') %></td>
      </tr>
      <tr>
        <th>送料</th>
        <td>¥<%= @order.shopping_cost %></td>
      </tr>

      <tr>
        <th>請求合計金額</th>
        <td>¥<%= @order.total_payment %></td>
      </tr>
    </tbody>
  </table>