config/routes.rb
Rails.application.routes.draw do
  # customer側ルーティング
   devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    root 'homes#top'
    get 'about' => 'homes#about'
   end

  namespace :customers do
   resources :items, only: [:show]
   resources :genres, only: [:show]
   get 'show' => 'customers#show'
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
   get 'orders/complete' => 'orders#complete'
   post 'orders/comfirm' => 'orders#comfirm'
   resources :orders, only: [:new, :create, :index, :show]
   resources :cart_items, only: [:index, :create, :update, :destroy]
   delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
   resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  # admin側ルーティング
   devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'orders#index'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
  
  
  # 退会
    def active_for_authentication?
      super && (self.is_deleted == false)
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  attachment :image
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price_without_tax, presence: true

  ## 消費税を求めるメソッド
  def with_tax_price
      (price_without_tax * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/models/project.rb
class Project < ApplicationRecord
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin then
        admins_root_path
      when Customer then
        root_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    #ViewのFormで取得したパラメータをモデルに渡す
    @projects = Project.search(params[:search])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
        <div class="container-footer">
          <div class="small text-center text-muted" style="margin: 50px 0;">Copyright © 
          </div>
        </div>
</footer>

app/views/layouts/_header.html.erb
<body class="d-flex flex-column vh-100">
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand" href="/"><%= link_to image_tag("Logo.jpg"), root_path, data: {"turbolinks" => false}, style: "font-family: HiraMinPro-W6; color: #000000;" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <!--カスタマーがログインしている時 -->
              <li style="font-family: HiraMinPro-W6; margin-top: 15px;">
                <div style ="margin-right: 150px;">ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！</div>
              </li>
              <li class="nav-item"><%= link_to "マイページ", customers_show_path, class: "btn btn-light mb-3",  style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "商品一覧", items_path, class: "btn btn-light mb-3",  style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "カート", customers_cart_items_path, class: "btn btn-light mb-3",  style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, class: "btn btn-light mb-3",  method: :delete, style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

            <% elsif admin_signed_in? %>
            <!-- 管理者がログインしている時 -->
              <li class="nav-item"><%= link_to "商品一覧", admins_items_path, class: "btn btn-light mb-3", style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "会員一覧", admins_customers_path, class: "btn btn-light mb-3",  style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "注文履歴一覧", admins_orders_path, class: "btn btn-light mb-3",  style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "ジャンル一覧", admins_genres_path, class: "btn btn-light mb-3",  style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-light mb-3",  method: :delete %></li>

            <% else %>
            <!-- ログインしていない時 -->
              <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-light mb-3", style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "商品一覧", items_path, class: "btn btn-light mb-3",　style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-light mb-3",　style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

              <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "btn btn-light mb-3",　style: "font-family: HiraMinPro-W6; color: #000000;" %></li>

            <% end %>
            </br>
          </ul>
        </div>
      </div>
    </nav>
  </header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

    <% if customer_signed_in? %>
      <body id="container" style="background-color: #EEEEEE; font-family: HiraMinPro-W6; color: #000000;">
        <!-- ヘッダー -->
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        <!-- Body部分 -->
        <div class="container" style="margin-top: 20px;">
          <%= yield %>
        </div>
        <!-- Footer -->
        <%= render "layouts/footer" %>
      </body>
      
    <% elsif admin_signed_in? %>
      <body id="container" style="background-color: #EEEEEE; font-family: HiraMinPro-W6; color: #000000;">
        <!-- ヘッダー -->
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        <!-- Body部分 -->
        <div class="container" style="margin-top: 20px;">
          <%= yield %>
        </div>
        <!-- Footer -->
        <%= render "layouts/footer" %>
      </body>
      
    <% else %>
      <body id="container" style="background-color: #EEEEEE; font-family: HiraMinPro-W6; color: #000000;">
        <!-- ヘッダー -->
        <div id="header"><%= render "layouts/header" %></div>
        <!-- Body部分 -->
        <div classtyle="margin-top: 20px;">
          <%= yield %>
        </div>
        <!-- Footer -->
        <div id="footer"><%= render "layouts/footer" %></div>
      </body>
    <% end %>
</html>